const MILLISECOND = 1 / 1000
const MILLISECONDS_PER_SECOND = 1000
const MINUTES_PER_HOUR = 60
const SECONDS_PER_MINUTE = 60
const SECONDS_PER_DAY = 86400
const HOURS_PER_DAY = 24
const DAYS_PER_WEEK = 7
const MONTHS_PER_YEAR = 12
const DAYS_PER_YEAR = 365
const DAYS_PER_LEAP_YEAR = 366
const YEARS_PER_DECADE = 10
const DAYS_PER_AVERAGE_MONTH = 30
const MAX_DAYS_PER_MONTH = 31
const LOWEST_DAYS_PER_MONTH = 28
const DAYS_PER_LEAP_MONTH = 29

const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_SECOND * 60 * 60
const MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY
const SECONDS_PER_HOUR = SECONDS_PER_DAY / HOURS_PER_DAY
const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * SECONDS_PER_MINUTE
const MILLISECONDS_PER_DAY = MILLISECONDS_PER_HOUR * HOURS_PER_DAY
const MILLISECONDS_PER_WEEK = MILLISECONDS_PER_DAY * DAYS_PER_WEEK
const MILLISECONDS_PER_YEAR = MILLISECONDS_PER_DAY * 365.24
const MILLISECONDS_PER_NORMAL_YEAR = MILLISECONDS_PER_DAY * DAYS_PER_YEAR
const MILLISECONDS_PER_LEAP_YEAR = MILLISECONDS_PER_DAY * DAYS_PER_LEAP_YEAR
const MILLISECONDS_PER_DECADE = YEARS_PER_DECADE * MILLISECONDS_PER_YEAR
const MILLISECONDS_PER_HALF_YEAR = MILLISECONDS_PER_YEAR / 2
const MILLISECONDS_PER_AVERAGE_MONTH = MILLISECONDS_PER_YEAR / MONTHS_PER_YEAR

module.exports = {
  MILLISECOND,
  MILLISECONDS_PER_SECOND,
  SECONDS_PER_MINUTE,
  SECONDS_PER_HOUR,
  SECONDS_PER_DAY,
  MINUTES_PER_HOUR,
  MINUTES_PER_DAY,
  HOURS_PER_DAY,
  DAYS_PER_WEEK,
  DAYS_PER_YEAR,
  DAYS_PER_LEAP_YEAR,
  MONTHS_PER_YEAR,
  DAYS_PER_AVERAGE_MONTH,
  MAX_DAYS_PER_MONTH,
  LOWEST_DAYS_PER_MONTH,
  DAYS_PER_LEAP_MONTH,
  MILLISECONDS_PER_MINUTE,
  MILLISECONDS_PER_DAY,
  MILLISECONDS_PER_HOUR,
  MILLISECONDS_PER_WEEK,
  MILLISECONDS_PER_YEAR,
  MILLISECONDS_PER_NORMAL_YEAR,
  MILLISECONDS_PER_LEAP_YEAR,
  MILLISECONDS_PER_DECADE,
  MILLISECONDS_PER_HALF_YEAR,
  MILLISECONDS_PER_AVERAGE_MONTH
}
